In [2]:
print("hello world")

hello world


this is a comment

# title 1
## section1
### paragraph1

In [3]:
import numpy as np

In [4]:
my_list = [100,200,300]
print(my_list)

[100, 200, 300]


In [5]:
my_arr = np.array(my_list)
print(my_arr)

[100 200 300]


In [6]:
type(my_arr)

numpy.ndarray

In [8]:
my_arr[0:2]

array([100, 200])

In [9]:
day1_temp = [30,50,45]
day2_temp = [50,80,60]
day3_temp = [70,100,80]

In [10]:
temp_matrix = np.array([day1_temp, day2_temp, day3_temp])
print(temp_matrix)

[[ 30  50  45]
 [ 50  80  60]
 [ 70 100  80]]


In [11]:
print(temp_matrix[1,1])

80


In [14]:
temp_matrix.max(axis=1)

array([ 50,  80, 100])

In [15]:
np.random.seed(100)

In [16]:
np.random.random((3,3))

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912],
       [0.67074908, 0.82585276, 0.13670659]])

In [17]:
np.random.randint(0,10,(3,3))

array([[8, 4, 0],
       [9, 6, 2],
       [4, 1, 5]])

In [18]:
np.random.normal(0,1,(3,3))

array([[ 1.01106614, -1.44077118,  0.98056914],
       [ 1.37699631, -0.23028509,  0.48092412],
       [-1.26691058,  0.27100509,  2.14076322]])